version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./game.db:/root/game.db
    environment:
      - OAUTH2_CLIENT_ID=your_client_id
      - OAUTH2_CLIENT_SECRET=your_client_secret
      - LOG_LEVEL=development